/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mapp;

import java.util.Scanner;

import static test_lib.MathFunctions.sumOdd;
import static test_lib.StringFunctions.printHelloWorld;
import test_lib.Menu;

public class App {

    public static void main(String[] args) {
        
        Menu m = new Menu(System.out, new Scanner(System.in, "UTF-8"));

        boolean quit = false;
        while (!quit) {
          switch (m.doMenu()) {
            case DoStuff:
              printHelloWorld(System.out);
              System.out.println("Sum of odd numbers in {0, 1, 2, 3} is: " + sumOdd(new int[] {0, 1, 2, 3}));
            break;
            default:
              quit = true;
            break;
          }
        }
    }
}
